version: '3.7'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - ~/mongo_data3:/data/db
    environment:
      - MONGO_INITDB_DATABASE=LucForTechJogos
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=6504
    ports:
      - 27017:27017